baseURL=http://demo.guru99.com/v4/index.php
username=mngr136913
password=abc321!
chromepath=C:\\Users\\Vimal\\chromedriver_win32\\chromedriver.exe
firefoxpath =C:\\Users\\Vimal\\geckodriver-v0.27.0-win64\\geckodriver.exe
