baseURL=http://demo.guru99.com/v4/index.php
username=mngr284542
password=anutAsa
chromepath=C:\\Users\\Vimal\\chromedriver_win32\\chromedriver.exe
firefoxpath =C:\\Users\\Vimal\\geckodriver-v0.27.0-win64\\geckodriver.exe
/*
mngr284777-bUjedAs
mngr284820-EpAqupA
*/
